name: university_map
description: A Flutter project for an indoor university map.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Make sure this matches your Dart SDK version


dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0  # Ensure this is the correct version
  latlong2: ^0.8.1      # Ensure this is the correct version

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0  # Check for the latest version

flutter:
  uses-material-design: true
